@local = http://localhost:3000


GET {{local}}/home

###
GET {{local}}/api/messages

###
GET {{local}}/api/messages/4f9be8e6-5055-412a-926e-11c73313beab

###
POST {{local}}/api/messages?message=ad111111111111111

###
DELETE  {{local}}/api/messages


###
POST  {{local}}/daniel/a/b/c