POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "userId": 3, 
    "title": "hello", 
    "body": "bye"
}

###
GET https://google.com/search?q=cute kittens

###
GET https://static.boredpanda.com/blog/wp-content/uploads/2016/08/cute-kittens-7-57b30aa10707a__605.jpg
